server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    # F4 : en-têtes de sécurité
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Toutes les routes inconnues → index.html (laisse React gérer la route)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache long pour les fichiers statiques (perf)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}